package com.example.shared.db

import com.squareup.sqldelight.db.SqlDriver

// The SQLDelight-generated Database interface will be generated under this package
// after Gradle builds. Use this type alias to avoid hardcoding the generated class name
// in other common code until SQLDelight generates it.

// Provide an expect factory to create a platform-specific SqlDriver.
expect class DatabaseDriverFactory {
    fun createDriver(): SqlDriver
}

// Example: consumers can create the database like:
// val driver = DatabaseDriverFactory().createDriver()
// val database = PickleTrackDatabase(driver) // PickleTrackDatabase generated by SQLDelight
